name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Copy index.html (and any other necessary files) to the dist folder
      - name: Copy index.html to dist folder
        run: |
          mkdir dist
          cp index.html dist/

      # Update pages artifact
      - name: Update pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
